name: First Workflow
on: [push]
jobs:
    run-shell-commands:
        run-on: ubuntu-latest
        steps:
          - name: echo a string
            run: echo "Hello world"
          - name: "Multiname command"
            run: | 
                node -v 
                npm -v     